version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_MOCKSERVER_URL=http://localhost:1080
    depends_on:
      - mockserver

  mockserver:
    image: mockserver/mockserver:latest
    ports:
      - "1080:1080"
